version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./graphql-server
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./graphql-server:/app

  frontend:
    build:
      context: ./graphql-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./graphql-frontend:/app
    working_dir: /app
    command: ["npm", "start"]

volumes:
  postgres_data:
